# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install node.js'


# - script: |
#     sudo apt-get install npm
#     sudo npm run build
#   displayName: 'npm install and build'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'serv-snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'install-docker'
    organization: 'b3b56003-44ae-4d7e-adf3-56464f1747de'
