# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    displayName: 'install node.js'

steps:
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'serv-snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'install-docker'
    organization: '415d81f1-388d-4f85-9344-298a837e88c1'
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
